alias g='git'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m '
alias gp='git push'
alias gco='git checkout'
alias gb'git branch'
alias gd='git diff'
alias gl='git log'
alias dotcommit="git add . && git commit -m '.'"
alias gac='git add . && git commit -m '
alias gwt='git worktree'
alias gwta='git worktree add'
alias gwtr='git worktree remove'
alias gw='git worktree list'
