alias g='git'
alias gi='git init'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m '
alias gp='git push'
alias gb='git branch'
alias gco='git checkout'
alias gm'git merge '
alias gd='git diff'
alias gl='git log'
alias commit="git add . && git commit -m ' Auto commit script ran '"
alias push="git add . && git commit -m 'Auto commit + push script ran' && git push"
alias gwt='git worktree'
alias gwta='git worktree add'
alias gwtr='git worktree remove'
alias gw='git worktree list'
